
#
# Makefile for lab 7, part 2
#

CC  = gcc
CXX = g++

CFLAGS   = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)


.PHONY: default
default: http-server 

# header dependency
## mdb-lookup-server.o: mdb.h



.PHONY: clean
clean:
	rm -f *.o *~ a.out core http-server

.PHONY: all
all: clean default



